import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import { FileText, Loader2 } from "lucide-react";

interface DocumentPreviewData {
  name: string;
  preview: string;
}

export default function DocumentPreview() {
  const { id } = useParams();
  const [document, setDocument] = useState<DocumentPreviewData | null>(null);

  useEffect(() => {
    fetch(`http://localhost:8000/api/documents/preview/${id}`)
      .then((res) => res.json())
      .then((data) => setDocument(data));
  }, [id]);

  if (!document) {
    return (
      <div className="flex min-h-[60vh] items-center justify-center rounded-lg border border-zinc-200 bg-white shadow-sm">
        <div className="flex items-center gap-3 text-sm font-medium text-zinc-500">
          <Loader2 size={18} className="animate-spin text-[#A61E22]" />
          Loading document preview
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <header className="rounded-lg border border-zinc-200 bg-white p-6 shadow-sm">
        <div className="flex items-start gap-4">
          <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-lg bg-[#A61E22]/10 text-[#A61E22]">
            <FileText size={24} />
          </div>
          <div className="min-w-0">
            <p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#A61E22]">
              Document Preview
            </p>
            <h1 className="mt-1 truncate text-3xl font-semibold text-zinc-950">{document.name}</h1>
          </div>
        </div>
      </header>

      <section className="rounded-lg border border-zinc-200 bg-white shadow-sm">
        <div className="border-b border-zinc-200 px-6 py-4">
          <h2 className="text-base font-semibold text-zinc-950">Extracted Content</h2>
          <p className="mt-1 text-sm text-zinc-500">Preview generated by the existing backend document endpoint.</p>
        </div>

        <pre className="max-h-[64vh] overflow-auto whitespace-pre-wrap p-6 text-sm leading-7 text-zinc-800 kms-scrollbar">
          {document.preview}
        </pre>
      </section>
    </div>
  );
}

